In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("heart.csv")

In [3]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
df.shape

(918, 12)

In [5]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [9]:
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [12]:
df["ChestPainType"].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [13]:
df.ChestPainType.value_counts()

ASY    496
NAP    203
ATA    173
TA      46
Name: ChestPainType, dtype: int64

# outliers using z score

In [14]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
76    32   M           ASY        118          529          0     Normal   
149   54   M           ASY        130          603          1     Normal   
616   67   F           NAP        115          564          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
76     130              N      0.0     Flat             1  
149    125              Y      1.0     Flat             1  
616    160              N      1.6     Flat             0

In [15]:
df.shape

(918, 12)

In [22]:
df1 = df[df.Cholesterol<=(df.Cholesterol.mean()+3*df.Cholesterol.std())]

In [23]:
df1.shape

(915, 12)

In [24]:
df[df.MaxHR>(df.MaxHR.mean()+3*df.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [27]:
df[df.FastingBS>(df.FastingBS.mean()+3*df.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [28]:
df[df.Age>(df.Age.mean()+3*df.Age.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [29]:
df[df.Oldpeak>(df.Oldpeak.mean()+3*df.Oldpeak.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
166   50   M           ASY        140          231          0         ST   
702   59   M            TA        178          270          0        LVH   
771   55   M           ASY        140          217          0     Normal   
791   51   M           ASY        140          298          0     Normal   
850   62   F           ASY        160          164          0        LVH   
900   58   M           ASY        114          318          0         ST   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
166    140              Y      5.0     Flat             1  
702    145              N      4.2     Down             0  
771    111              Y      5.6     Down             1  
791    122              Y      4.2     Flat             1  
850    145              N      6.2     Down             1  
900    140              N      4.4     Down             1

In [30]:
df2 = df1[df1.Oldpeak<=(df1.Oldpeak.mean()+3*df1.Oldpeak.std())]

In [32]:
df2.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [33]:
df2.shape

(909, 12)

In [34]:
df["RestingECG"].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [35]:
df["ST_Slope"].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [36]:
df["Sex"].unique()

array(['M', 'F'], dtype=object)

In [45]:
df3 = df2.copy()
df3.Sex.replace({"M":0,"F":1},inplace =True)
df3.ST_Slope.replace({"Up":1,"Flat":2,"Down":3},inplace = True)
df3.RestingECG.replace({"Normal":1,"ST":2,"LVH":3},inplace = True)
df3.ExerciseAngina.replace({"N":0,"Y":1},inplace = True)

In [46]:
df3.head()

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0           ATA        140          289          0           1   
1   49    1           NAP        160          180          0           1   
2   37    0           ATA        130          283          0           2   
3   48    1           ASY        138          214          0           1   
4   54    0           NAP        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         1             0  
1    156               0      1.0         2             1  
2     98               0      0.0         1             0  
3    108               1      1.5         2             1  
4    122               0      0.0         1             0

# HOT encoding

In [51]:
from sklearn .preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df3

dfle.ChestPainType = le.fit_transform(dfle.ChestPainType)


In [52]:
dfle.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0              1        140          289          0           1   
1   49    1              2        160          180          0           1   
2   37    0              1        130          283          0           2   
3   48    1              0        138          214          0           1   
4   54    0              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         1             0  
1    156               0      1.0         2             1  
2     98               0      0.0         1             0  
3    108               1      1.5         2             1  
4    122               0      0.0         1             0

In [53]:
x = dfle.drop(["HeartDisease"],axis = 1)
y = dfle.HeartDisease


In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [64]:
x_scaled = scaler.fit_transform(x)
x_scaled[:3]

array([[-1.43228867, -0.51576808,  0.22703297,  0.4140165 ,  0.85233413,
        -0.55320383, -0.74680534,  1.37760633, -0.82287409, -0.84660886,
        -1.04651643],
       [-0.47770182,  1.93885593,  1.27461148,  1.49623359, -0.16029364,
        -0.55320383, -0.74680534,  0.75099471, -0.82287409,  0.13698962,
         0.61366408],
       [-1.75048428, -0.51576808,  0.22703297, -0.12709205,  0.79659315,
        -0.55320383,  0.49650245, -1.5204724 , -0.82287409, -0.84660886,
        -1.04651643]])

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,stratify = y,random_state = 10)

In [59]:
len(x_train)

727

In [60]:
len(x_test)

182

In [61]:
dfle["HeartDisease"].value_counts()

1    501
0    408
Name: HeartDisease, dtype: int64

In [63]:
ratio = 408/501
ratio

0.8143712574850299

In [66]:
y_train.value_counts()

1    375
0    306
Name: HeartDisease, dtype: int64

In [67]:
ratio2 = 306/375

In [68]:
ratio2

0.816

In [79]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
scores = cross_val_score(SVC(),x,y,cv=5)
scores.mean()

0.6852953676158096

In [84]:
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier(base_estimator = SVC(),n_estimators= 100,max_samples=0.8,oob_score = True,random_state = 0)

In [85]:
bag_model.fit(x_train,y_train)

C:\Users\abc\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=0)

In [86]:
bag_model.oob_score_

0.8634361233480177

In [71]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
scores = cross_val_score(DecisionTreeClassifier(),x,y,cv = 5)

In [72]:
scores

array([0.76923077, 0.76373626, 0.77472527, 0.76923077, 0.65745856])

In [73]:
scores.mean()

0.7468763280917976

In [75]:
##Bagging classifier we also see the score
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier(base_estimator = DecisionTreeClassifier(),n_estimators= 100,max_samples=0.8,oob_score = True,random_state = 0)

In [76]:
bag_model.fit(x_train,y_train)

C:\Users\abc\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=0)

In [77]:
bag_model.oob_score_

0.8458149779735683

In [88]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
rf = model_rf.fit(x_train,y_train)
score = model.score(x_test,y_test)


In [89]:
score

0.868421052631579

In [90]:
from sklearn.decomposition import PCA
pca = PCA(.95)
x_pca = pca.fit_transform(x)
x_pca

array([[ 93.94004917, -29.12770235],
       [-15.50048614, -13.60738134],
       [ 83.33752997,  38.43742714],
       ...,
       [-67.50916885,  17.29870505],
       [ 40.83028485, -33.37969267],
       [-19.78764325, -37.13697973]])

In [92]:
x_pca_train,x_pca_test,y_train,y_test = train_test_split(x_pca,y,test_size = 0.2,random_state = 30)

In [93]:
from sklearn.tree import DecisionTreeClassifier
model_de = DecisionTreeClassifier()
model_de.fit(x_pca_train,y_train)

DecisionTreeClassifier()

In [94]:
model_de.score(x_pca_test,y_test)

0.6538461538461539